package com.xiaohao.cms.mapper;

import com.xiaohao.cms.model.Leave;
import com.xiaohao.cms.model.LeaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int countByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int deleteByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int insertSelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    List<Leave> selectByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    Leave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByExampleSelective(@Param("record") Leave record, @Param("example") LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByExample(@Param("record") Leave record, @Param("example") LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByPrimaryKey(Leave record);
}