package com.xiaohao.cms.mapper;

import com.xiaohao.cms.model.AccessLog;
import com.xiaohao.cms.model.AccessLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int countByExample(AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int deleteByExample(AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int insert(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int insertSelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    List<AccessLog> selectByExampleWithBLOBs(AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    List<AccessLog> selectByExample(AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    AccessLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByExampleSelective(@Param("record") AccessLog record, @Param("example") AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") AccessLog record, @Param("example") AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByExample(@Param("record") AccessLog record, @Param("example") AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByPrimaryKeySelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_log
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByPrimaryKey(AccessLog record);
}