package com.xiaohao.cms.mapper;

import com.xiaohao.cms.model.Mix;
import com.xiaohao.cms.model.MixExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int countByExample(MixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int deleteByExample(MixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int insert(Mix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int insertSelective(Mix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    List<Mix> selectByExampleWithBLOBs(MixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    List<Mix> selectByExample(MixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    Mix selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") Mix record, @Param("example") MixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Mix record, @Param("example") MixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByExample(@Param("record") Mix record, @Param("example") MixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByPrimaryKeySelective(Mix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Mix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByPrimaryKey(Mix record);
}