package com.xiaohao.cms.mapper;

import com.xiaohao.cms.model.MixSidebar;
import com.xiaohao.cms.model.MixSidebarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MixSidebarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int countByExample(MixSidebarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int deleteByExample(MixSidebarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int insert(MixSidebar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int insertSelective(MixSidebar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    List<MixSidebar> selectByExample(MixSidebarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    MixSidebar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") MixSidebar record, @Param("example") MixSidebarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByExample(@Param("record") MixSidebar record, @Param("example") MixSidebarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByPrimaryKeySelective(MixSidebar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mix_sidebar
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    int updateByPrimaryKey(MixSidebar record);
}