package com.xiaohao.cms.mapper;

import com.xiaohao.cms.model.Pages;
import com.xiaohao.cms.model.PagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int countByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int deleteByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int insert(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int insertSelective(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    List<Pages> selectByExampleWithBLOBs(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    List<Pages> selectByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    Pages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByExampleSelective(@Param("record") Pages record, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Pages record, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByExample(@Param("record") Pages record, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByPrimaryKeySelective(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pages
     *
     * @mbggenerated Sat Aug 16 21:14:11 CST 2014
     */
    int updateByPrimaryKey(Pages record);

    /**
     *
     * @return
     */
    List queryListDiy();
}