package com.xiaohao.cms.mapper;

import com.xiaohao.cms.model.ProductSub;
import com.xiaohao.cms.model.ProductSubExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int countByExample(ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int deleteByExample(ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int insert(ProductSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int insertSelective(ProductSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    List<ProductSub> selectByExampleWithBLOBs(ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    List<ProductSub> selectByExample(ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    ProductSub selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByExampleSelective(@Param("record") ProductSub record, @Param("example") ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") ProductSub record, @Param("example") ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByExample(@Param("record") ProductSub record, @Param("example") ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByPrimaryKeySelective(ProductSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(ProductSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_sub
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    int updateByPrimaryKey(ProductSub record);
}