package com.xiaohao.cms.model;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.user
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.psw
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private String psw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.isAdmin
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private Boolean isAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.user
     *
     * @return the value of t_admin.user
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.user
     *
     * @param user the value for t_admin.user
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.psw
     *
     * @return the value of t_admin.psw
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public String getPsw() {
        return psw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.psw
     *
     * @param psw the value for t_admin.psw
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setPsw(String psw) {
        this.psw = psw == null ? null : psw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.isAdmin
     *
     * @return the value of t_admin.isAdmin
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.isAdmin
     *
     * @param isAdmin the value for t_admin.isAdmin
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
}