package com.xiaohao.cms.model;

public class Mix {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix.id
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix.name
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix.sort
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix.pid
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix.value
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix.id
     *
     * @return the value of t_mix.id
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix.id
     *
     * @param id the value for t_mix.id
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix.name
     *
     * @return the value of t_mix.name
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix.name
     *
     * @param name the value for t_mix.name
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix.sort
     *
     * @return the value of t_mix.sort
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix.sort
     *
     * @param sort the value for t_mix.sort
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix.pid
     *
     * @return the value of t_mix.pid
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix.pid
     *
     * @param pid the value for t_mix.pid
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix.value
     *
     * @return the value of t_mix.value
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix.value
     *
     * @param value the value for t_mix.value
     *
     * @mbggenerated Fri Sep 26 10:03:16 CST 2014
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}