package com.xiaohao.cms.model;

public class MixSidebar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix_sidebar.id
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix_sidebar.name
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix_sidebar.pid
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mix_sidebar.sort
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix_sidebar.id
     *
     * @return the value of t_mix_sidebar.id
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix_sidebar.id
     *
     * @param id the value for t_mix_sidebar.id
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix_sidebar.name
     *
     * @return the value of t_mix_sidebar.name
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix_sidebar.name
     *
     * @param name the value for t_mix_sidebar.name
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix_sidebar.pid
     *
     * @return the value of t_mix_sidebar.pid
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix_sidebar.pid
     *
     * @param pid the value for t_mix_sidebar.pid
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mix_sidebar.sort
     *
     * @return the value of t_mix_sidebar.sort
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mix_sidebar.sort
     *
     * @param sort the value for t_mix_sidebar.sort
     *
     * @mbggenerated Thu Sep 25 17:37:58 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}