package com.xiaohao.cms.model;

public class Pages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.id
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.title
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.author
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.module
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.time
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Long time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.sort
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.isProduct
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Boolean isproduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.isMenu
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Boolean ismenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.isSecondaryMenu
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Boolean issecondarymenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.pid
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.isNews
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private Boolean isnews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.ext_url
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private String extUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pages.content
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.id
     *
     * @return the value of t_pages.id
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.id
     *
     * @param id the value for t_pages.id
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.title
     *
     * @return the value of t_pages.title
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.title
     *
     * @param title the value for t_pages.title
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.author
     *
     * @return the value of t_pages.author
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.author
     *
     * @param author the value for t_pages.author
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.module
     *
     * @return the value of t_pages.module
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.module
     *
     * @param module the value for t_pages.module
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.time
     *
     * @return the value of t_pages.time
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.time
     *
     * @param time the value for t_pages.time
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.sort
     *
     * @return the value of t_pages.sort
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.sort
     *
     * @param sort the value for t_pages.sort
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.isProduct
     *
     * @return the value of t_pages.isProduct
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Boolean getIsproduct() {
        return isproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.isProduct
     *
     * @param isproduct the value for t_pages.isProduct
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setIsproduct(Boolean isproduct) {
        this.isproduct = isproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.isMenu
     *
     * @return the value of t_pages.isMenu
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Boolean getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.isMenu
     *
     * @param ismenu the value for t_pages.isMenu
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setIsmenu(Boolean ismenu) {
        this.ismenu = ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.isSecondaryMenu
     *
     * @return the value of t_pages.isSecondaryMenu
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Boolean getIssecondarymenu() {
        return issecondarymenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.isSecondaryMenu
     *
     * @param issecondarymenu the value for t_pages.isSecondaryMenu
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setIssecondarymenu(Boolean issecondarymenu) {
        this.issecondarymenu = issecondarymenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.pid
     *
     * @return the value of t_pages.pid
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.pid
     *
     * @param pid the value for t_pages.pid
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.isNews
     *
     * @return the value of t_pages.isNews
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public Boolean getIsnews() {
        return isnews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.isNews
     *
     * @param isnews the value for t_pages.isNews
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setIsnews(Boolean isnews) {
        this.isnews = isnews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.ext_url
     *
     * @return the value of t_pages.ext_url
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public String getExtUrl() {
        return extUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.ext_url
     *
     * @param extUrl the value for t_pages.ext_url
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setExtUrl(String extUrl) {
        this.extUrl = extUrl == null ? null : extUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pages.content
     *
     * @return the value of t_pages.content
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pages.content
     *
     * @param content the value for t_pages.content
     *
     * @mbggenerated Thu Sep 25 15:21:12 CST 2014
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}