package com.xiaohao.cms.model;

public class ProductSub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_sub.id
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_sub.name
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_sub.pic
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_sub.category
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_sub.sort
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_sub.description
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_sub.id
     *
     * @return the value of t_product_sub.id
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_sub.id
     *
     * @param id the value for t_product_sub.id
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_sub.name
     *
     * @return the value of t_product_sub.name
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_sub.name
     *
     * @param name the value for t_product_sub.name
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_sub.pic
     *
     * @return the value of t_product_sub.pic
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_sub.pic
     *
     * @param pic the value for t_product_sub.pic
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_sub.category
     *
     * @return the value of t_product_sub.category
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_sub.category
     *
     * @param category the value for t_product_sub.category
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_sub.sort
     *
     * @return the value of t_product_sub.sort
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_sub.sort
     *
     * @param sort the value for t_product_sub.sort
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_sub.description
     *
     * @return the value of t_product_sub.description
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_sub.description
     *
     * @param description the value for t_product_sub.description
     *
     * @mbggenerated Wed Sep 24 15:33:03 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}